# Generated by Django 6.0.1 on 2026-03-16 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Online_App', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examapp.studentprofile'),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='student_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_details', to='Online_App.studentmarks'),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Online_App.studentexamsubmission'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_App.schoolclass'),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_App.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_App.subject'),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Online_App.subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_App.subject'),
        ),
        migrations.AddField(
            model_name='teachernotification',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Online_App.studentexamsubmission'),
        ),
        migrations.AddField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_App.chapter'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_App.topic'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='teacherpapersettings',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachernotification',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexamsubmission',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexamsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionusagelog',
            name='used_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagepurchase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedquestionpaper',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedquestionpaper',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biologyquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biology_questions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biologyquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biology_questions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoexamtemplate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_exam_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoexampaper',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_type': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='auto_exams_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teacherpapersettings',
            unique_together={('teacher',)},
        ),
        migrations.AddIndex(
            model_name='studentexamsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='Online_App__status_94e489_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsubmission',
            index=models.Index(fields=['student', 'status'], name='Online_App__student_10c08f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsubmission',
            index=models.Index(fields=['evaluation_status'], name='Online_App__evaluat_fcb72d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamsubmission',
            index=models.Index(fields=['student', 'evaluation_status'], name='Online_App__student_348751_idx'),
        ),
        migrations.AddIndex(
            model_name='questionusagelog',
            index=models.Index(fields=['content_type', 'object_id'], name='Online_App__content_d8dc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionusagelog',
            index=models.Index(fields=['used_at'], name='Online_App__used_at_c4da5d_idx'),
        ),
    ]
